### ISSUE TITLE
An error appears when trying to run the program.

### ISSUE THREAD

**Issue by falco93** [Sorrow446/Qo-DL-Reborn#1]
Hello sorrow and dash, tried your new qo-dl but a problem appear everytime i try to use it, i installed the requirements in requirements.txt. what i am doing wrong?
![Immagine](https://user-images.githubusercontent.com/57359412/68128439-06ce6b80-ff18-11e9-95f8-9137e9c70a18.png)

**Comment by Sorrow446** [comment]
You messed something up in the "creds" section.

**Comment by falco93** [comment]
> You messed something up in the "creds" section.

i wrote my email and my ashed password but doesn't work anyway, i didn't touch space and the like, but still doesn't work
