### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by fominator** [Sorrow446/Qo-DL-Reborn#11]
Both versions don't work now.

**Comment by Sorrow446** [comment]
This isn't helpful at all. Reply with the traceback.

**Comment by fominator** [comment]
Last version simply close after start. First version started showing this text a few hours ago

Traceback (most recent call last):
  File "qo-dl_reborn.py", line 541, in <module>
  File "qo-dl_reborn.py", line 424, in main
  File "qo-dl_reborn.py", line 354, in download
  File "qopy\qopy.py", line 99, in get_track_url
  File "qopy\qopy.py", line 78, in api_call
  File "site-packages\requests\models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.qobuz.com/api.json/0.2/track/getFileUrl?request_ts=1573260116.8416731&request_sig=7163f303136ca0fc905d7a10f99505c4&track_id=6803608&format_id=27&intent=stream

An exception has occurred. Press enter to exit.

**Comment by falco93** [comment]
> Last version simply closes after start. First version started to show this text a few hours ago
> 
> Traceback (most recent call last):
> File "qo-dl_reborn.py", line 541, in
> File "qo-dl_reborn.py", line 424, in main
> File "qo-dl_reborn.py", line 354, in download
> File "qopy\qopy.py", line 99, in get_track_url
> File "qopy\qopy.py", line 78, in api_call
> File "site-packages\requests\models.py", line 940, in raise_for_status
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.qobuz.com/api.json/0.2/track/getFileUrl?request_ts=1573260116.8416731&request_sig=7163f303136ca0fc905d7a10f99505c4&track_id=6803608&format_id=27&intent=stream
> 
> An exception has occurred. Press enter to exit.

If you are using windows try to download the old qo-dl_reborn_x86, start it then close it, then start the new one, it solved this issue for me.

**Comment by fominator** [comment]
> > Last version simply closes after start. First version started to show this text a few hours ago
> > Traceback (most recent call last):
> > File "qo-dl_reborn.py", line 541, in
> > File "qo-dl_reborn.py", line 424, in main
> > File "qo-dl_reborn.py", line 354, in download
> > File "qopy\qopy.py", line 99, in get_track_url
> > File "qopy\qopy.py", line 78, in api_call
> > File "site-packages\requests\models.py", line 940, in raise_for_status
> > requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.qobuz.com/api.json/0.2/track/getFileUrl?request_ts=1573260116.8416731&request_sig=7163f303136ca0fc905d7a10f99505c4&track_id=6803608&format_id=27&intent=stream
> > An exception has occurred. Press enter to exit.
> 
> If you are using windows try to download the old qo-dl_reborn_x86, start it then close it, then start the new one, it solved this issue for me.

**Comment by fominator** [comment]
no it doesn't help

**Comment by fominator** [comment]
i closed it by mistake

**Comment by fominator** [comment]
i don't know what has happend but it works again

**Comment by Sorrow446** [comment]
Here's how I coded it:

If no qopy_cfg.json, fetch new ID & sec, make cfg file and write to it.
if ID or secret is bad, fetch new ID & sec.

**Comment by fominator** [comment]
> Here's how I coded it:
> 
> If no qopy_cfg.json, fetch new ID & sec, make cfg file and write to it.
> If ID or sec is bad, fetch new ID & sec and write to cfg file.

ok, thank you, i think this issue can be closed
