### ISSUE TITLE
Downloading problems on windows.

### ISSUE THREAD

**Issue by falco93** [Sorrow446/Qo-DL-Reborn#17]
There are problems when downloading some albums with windows, i think it's because of the "..." at the end, could you make a fix like you did with the older version of Qo-DL? maybe by inserting the date of the album at the end of the folder name? that seemed to have fixed that error back then.
As you can see, every album with a "..." doesn't work, here's an example.
![](https://user-images.githubusercontent.com/57359412/68502447-b2512600-0260-11ea-8a0e-9b573b024e44.png)

**Comment by Sorrow446** [comment]
Dupe. https://github.com/Sorrow446/Qo-DL-Reborn/issues/12
