### ISSUE TITLE
Changing folder name on windows to download album with "..."

### ISSUE THREAD

**Issue by falco93** [Sorrow446/Qo-DL-Reborn#18]
Sorry sorrow, i saw you said to manually change the folder name to make things work
Yep. Just add them to the filename string replace.

_Originally posted by @Sorrow446 in https://github.com/Sorrow446/Qo-DL-Reborn/issues/12#issuecomment-552142783_
But where and how to do it? in config.json there's no way to do it, do i have to open the program and edit with idle? if so what do i have to change and how? i am trying to find a way to do it but nothing works. sorry for the stupid question.

**Comment by Sorrow446** [comment]
No problem. From my understanding, this problem only happens with the filename ends with three full stops. This should work.

Line 170:

Before:
```
def sanitize(f):
	if get_os():
		return re.sub(r'[\\/:*?"><|]', '-', f)
	else:
		return re.sub('/', '-', f)
```

After:
```
def sanitize(f):
	if get_os():
		return re.sub(r'[\\/:*?"><|...]', '-', f)
	else:
		return re.sub('/', '-', f)
```

**Comment by falco93** [comment]
> No problem. From my understanding, this problem only happens with the filename ends with three full stops. This should work.
> 
> Line 170:
> 
> Before:
> 
> ```
> def sanitize(f):
> 	if get_os():
> 		return re.sub(r'[\\/:*?"><|]', '-', f)
> 	else:
> 		return re.sub('/', '-', f)
> ```
> 
> After:
> 
> ```
> def sanitize(f):
> 	if get_os():
> 		return re.sub(r'[\\/:*?"><|\.+]', '-', f)
> 	else:
> 		return re.sub('/', '-', f)
> ```
> 
> Edit: this will also replace single full stops. Will reply with something better later.

This works! But strangely, this album still can't be downloaded, strange because it download just fine in the older version, here's a screen, what may it be the cause?
![](https://user-images.githubusercontent.com/57359412/68502547-f3493a80-0260-11ea-9754-aa0fbb4d577c.png)
Thanks as always.

**Comment by Sorrow446** [comment]
Damn. Must not be the full stops then. I see that your drive letter doesn't have a backslash on it. Do you have download_dir on?

**Comment by falco93** [comment]
> Damn. Must not be the full stops then. I see that your drive letter doesn't have a backslash on it.

Yes, for this album there's something different that's causing problems, but i don't understand what it may be. it's strange because the old version didn't give any problem while downloading it.
What do you think may be? is there something i can do about it?
