### ISSUE TITLE
A question about these rippers.

### ISSUE THREAD

**Issue by falco93** [Sorrow446/Qo-DL-Reborn#24]
Sorrow, is there any loss in quality compared to stremable ones? i mean, i am listening right now tracks downloaded with HRA-DL, but there seems to be less bass compared to the stremable ones, are they just my ears or there is something wrong? same about Qo-DL.
There's no change in the streamable files?

**Comment by Sorrow446** [comment]
Hello. I'm not sure on this. You'd need to get in touch with these companies yourself. Qo-DL doesn't modify the audio in any way.

**Comment by falco93** [comment]
> Hello. I'm not sure on this. You'd need to get in touch with these companies yourself. Qo-DL doesn't modify the audio in any way.

Thank you Sorrow.
The same goes for HRA-DL right, it doesn't modify audio in any way too?

**Comment by sskinhg** [comment]
You Could just download Adobe Audition, then input your file(better be a 24bit 44.1khz+ file) then the software will measure the Spectrogram and waveform of the file, if there's any frequency above 20khz, this file will more likely be a  lossless file.

**Comment by Sorrow446** [comment]
Yep, same applies for all of my tools. Untouched.

**Comment by falco93** [comment]
> You Could just download Adobe Audition, then input your file(better be a 24bit 44.1khz+ file) then the software will measure the Spectrogram and waveform of the file, if there's any frequency above 20khz, this file will more likely be a lossless file.

Thank you, for that i am using fakin the funk and spek and they seems to work fine, the majority of files are legit flac while others seems fake, but that's a problem with the sites and not with these apps.
And thank you again sorrow, i guess it's just my ears, maybe it's just a placebo effect and there's no difference with the bass. Thank you again.
