### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by LordEchos** [Sorrow446/Qo-DL-Reborn#29]
Can this be used for Mac and what are the instructions to run it in Terminal, thanks a lot!

**Comment by LETRA** [comment]
The Mac version has fewer functions than the windows version. You will use it more comfortably if you virtualize Windows with Parallels or Virtual Box and then run a precompiled package from there.

**Comment by LordEchos** [comment]
When I run it, I get:

 % ./qo-dl_reborn.py
Traceback (most recent call last):
  File "./qo-dl_reborn.py", line 13, in <module>
    import qopy
  File "/Users/home/Desktop/a/qopy/__init__.py", line 1, in <module>
    from .qopy import Client
  File "/Users/home/Desktop/a/qopy/qopy.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Sorrow446** [comment]
You're missing required libraries. You need to cd into Qo-DL's dir and do `pip3 install -r requirements.txt`

**Comment by LordEchos** [comment]
Thanks, works now. Much appreciated!
