### ISSUE TITLE
Error on Start

### ISSUE THREAD

**Issue by kzboray** [Sorrow446/Qo-DL-Reborn#35]
_____         ____  __       _____     _
|     |___ ___|    \|  |     | __  |___| |_ ___ ___ ___
|  |  | . |___|  |  |  |__   |    -| -_| . | . |  _|   |
|__  _|___|   |____/|_____|  |__|__|___|___|___|_| |_|_|
   |__|

Traceback (most recent call last):
  File "qo-dl_reborn.py", line 536, in <module>
  File "qo-dl_reborn.py", line 99, in parse_prefs
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

An exception has occurred. Press enter to exit.

**Comment by Sorrow446** [comment]
Download and fill in your conifg. https://raw.githubusercontent.com/Sorrow446/Qo-DL-Reborn/master/config.json
