### ISSUE TITLE
About Qo-dl

### ISSUE THREAD

**Issue by Xarchuser** [Sorrow446/Qo-DL-Reborn#8]
That's just a question, not a issue tbh. Why do you keep uploading Qo-DL on github lol. They'll ban it again, there are several alternatives such gitlab and notabug. I'm not complaining anything just warning you.

**Comment by Sorrow446** [comment]
Because I think it doesn't reduce the chances of it getting DMCA'd. Notabug aren't not gonna comply with a DMCA request if one comes their way.
