### ISSUE TITLE
Is the app still working?

### ISSUE THREAD

**Issue by falco93** [Sorrow446/Qo-DL-Reborn#9]
It's giving me an error about a wrong url with every album, it's just me?

**Comment by Sorrow446** [comment]
The URL input regex hasn't been changed. Reply with what you're inputting.

**Comment by falco93** [comment]
> The URL input regex hasn't been changed. Reply with what you're inputting.

![image](https://user-images.githubusercontent.com/57359412/68431664-11586180-01b3-11ea-88b7-0c532a235447.png)
Here it's a screenshot.

**Comment by edman84** [comment]
same with me

**Comment by Sorrow446** [comment]
That's an app secret issue. Reborn fetches the first app secret it gets of the four. I'll slap a hotfix up soon where it'll loop over all of them and find out which one's working.

**Comment by awsms** [comment]
> > The URL input regex hasn't been changed. Reply with what you're inputting.
> > Here it's a screenshot.
> > ![Immagine](https://user-images.githubusercontent.com/57359412/68431802-5c727480-01b3-11ea-8ef6-66aaa27c073f.png)

Arf, same here

**Comment by sskinhg** [comment]
Still the appsecret issue
Traceback (most recent call last):
  File "qo-dl_reborn.py", line 541, in <module>
  File "qo-dl_reborn.py", line 424, in main
  File "qo-dl_reborn.py", line 354, in download
  File "qopy\qopy.py", line 99, in get_track_url
  File "qopy\qopy.py", line 78, in api_call
  File "site-packages\requests\models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.qobuz.com/api.json/0.2/track/getFileUrl?request_ts=1573204696.8840091&request_sig=d4f5e67e3231176d3e026d2525523cf0&track_id=54098622&format_id=27&intent=stream

**Comment by awsms** [comment]
> Still the appsecret issue
> Traceback (most recent call last):
> File "qo-dl_reborn.py", line 541, in
> File "qo-dl_reborn.py", line 424, in main
> File "qo-dl_reborn.py", line 354, in download
> File "qopy\qopy.py", line 99, in get_track_url
> File "qopy\qopy.py", line 78, in api_call
> File "site-packages\requests\models.py", line 940, in raise_for_status
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.qobuz.com/api.json/0.2/track/getFileUrl?request_ts=1573204696.8840091&request_sig=d4f5e67e3231176d3e026d2525523cf0&track_id=54098622&format_id=27&intent=stream

Last commit was 4 days ago, of course it hasn't been fixed yet

**Comment by Sorrow446** [comment]
Please try this fix. Sorry for the trouble.
[400_fix.zip](https://github.com/Sorrow446/Qo-DL-Reborn/files/3824654/400_fix.zip)

**Comment by falco93** [comment]
> Please try this fix. Sorry for the trouble. Compiled build coming later on today if this is okay.
> [400_fix.zip](https://github.com/Sorrow446/Qo-DL-Reborn/files/3824654/400_fix.zip)

Now it's working! thanks sorrow.

**Comment by Sorrow446** [comment]
Great. You're welcome. I might do, but no guarantees. Haven't touched that in a long time.
